name: Build/Test Back-End

on:
  pull_request:
    branches:
    - master
    - sprints/*

env:
  NODE_VERSION: '12.18'

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test --if-present
